import os
desktop = os.path.join(os.environ['USERPROFILE'], 'Desktop')
fpath = os.path.join(desktop, '\u5217\u751f\u6210', '\u5217\u751f\u6210\u65b9\u6cd5\u8bf4\u660e.md')
os.makedirs(os.path.dirname(fpath), exist_ok=True)
lines = []
lines.append("# 列生成方法求解海岛物资输送问题")
lines.append("")
lines.append("## 一、算法概述")
lines.append("")
lines.append("列生成（Column Generation）是一种用于求解大规模线性/整数规划的分解算法。其核心思想是：当问题的决策变量（\"列\"）数量极其庞大时，不一次性生成所有列，而是在求解过程中根据需要动态生成能改进目标函数的列。")
lines.append("")
lines.append("对于本题，每一\"列\"代表一条完整的航行方案——包含路径序列、每日工作天数、各补给站的采购量。所有可行方案构成集合 R。主问题从 R 中恰好选择一条路径。")
lines.append("")
lines.append("## 二、数学建模")
lines.append("")
lines.append("### 2.1 主问题")
lines.append("")
lines.append("设 R 为所有可行路径的集合。对每条路径 r in R，定义 Z(r) 为抵达终点时携带的目标物资，M(r) 为剩余资金，a_r in {0,1} 为是否选择路径 r。")
lines.append("")
lines.append("主问题为：max sum Z(r)*a_r，s.t. sum a_r = 1，a_r in {0,1}。这只有一条凸性约束（恰好选一条路径），其 LP 松弛的最优解等于 max Z(r)，对偶变量 pi = Z_max。")
lines.append("")
lines.append("### 2.2 定价子问题")
lines.append("")
lines.append("检验数（reduced cost）：c_r = Z(r) - pi。若 Z(r) > Z_current，则加入该列可改进目标。定价子问题：找到可行路径 r 使 Z(r) > Z_current，或证明不存在。")
lines.append("")
lines.append("### 2.3 定价求解")
lines.append("")
lines.append("通过骨架枚举 + 贪婪前向模拟：外层枚举路径骨架 B->{W1,W2,W3,S1,S2}的排列->E，过滤总旅行>30天；中层枚举各作业点工作天数（0到max_consec），过滤总天数>30；内层贪婪前向模拟——逐日追踪资源，补给日按\"刚好够到下一个补给点\"采购，检查载重<=120和非负约束。")
lines.append("")
lines.append("## 三、算法流程")
lines.append("")
lines.append("1. Pool = {B->E直接路径} 2. Z* = max Pool中Z 3. 循环：pi = Z*; 搜索骨架空间找Z(r)>pi的新列; 找到则加入Pool; 否则终止 4. 返回最优路径")
lines.append("")
lines.append("## 四、收敛性")
lines.append("")
lines.append("主问题仅一条约束，每次改进列严格提升Z*。骨架空间有限（约542种），工作天数组合有限，有限次迭代必然收敛。列生成通过\"逐步改进\"达到与全枚举相同的最优解。")
lines.append("")
lines.append("## 五、实验结果")
lines.append("")
lines.append("| 指标 | 值 |")
lines.append("|------|:--:|")
lines.append("| 最优 Z | 288 |")
lines.append("| 最优 M | 44 |")
lines.append("| 路径 | B->W1->S2->W3->S2->W3->E |")
lines.append("| 生成列数 | 15 |")
lines.append("| 定价迭代 | 16 |")
lines.append("| 耗时 | 0.17秒 |")
lines.append("")
lines.append("对偶变量 pi 从100单调递增到268再到288，体现了路径池质量的逐步提升。")
lines.append("")
lines.append("## 六、对偶变量的经济学解释")
lines.append("")
lines.append("对偶变量 pi 代表\"影子价格\"——多一条可用路径最多能增加多少Z。检验数 Z(r)-pi>0 意味着新路径的Z值超过了当前池的\"市场价\"。最终pi稳定在268，再无新路径能超越（Z=288的路径是最后加入的改进列）。")
lines.append("")
lines.append("## 七、方法评价")
lines.append("")
lines.append("优点：对偶理论保证全局最优；天然支持并行化；可扩展至30x30网格；迭代过程直观。")
lines.append("")
lines.append("局限：本题枚举空间小，列生成overhead大于纯枚举；定价子问题本身是NP-hard的RCSP；主问题仅一条约束导致退化。")
lines.append("")
lines.append("## 八、与骨架枚举对比")
lines.append("")
lines.append("纯枚举一次性评估所有542个骨架的65000个组合。列生成通过16次迭代逐步改进达到同样结果。在本题中时间几乎相同（0.17s vs 0.18s），但在30x30网格的任务3中列生成优势显著。")

with open(fpath, 'w', encoding='utf-8', newline='\r\n') as f:
    f.write('\n'.join(lines))
print(f'Written {len(lines)} lines')