import os
desktop = os.path.join(os.environ['USERPROFILE'], 'Desktop')
fpath = os.path.join(desktop, '\u7ea6\u675f\u89c4\u5212', '\u7ea6\u675f\u89c4\u5212\u65b9\u6cd5\u8bf4\u660e.md')
os.makedirs(os.path.dirname(fpath), exist_ok=True)
lines = []
lines.append("# 约束规划方法求解海岛物资输送问题")
lines.append("")
lines.append("## 一、算法概述")
lines.append("")
lines.append("约束规划（Constraint Programming, CP）是一种求解组合优化问题的编程范式。与数学规划（LP/MILP）依赖线性松弛不同，CP 通过约束传播 + 系统搜索在离散决策变量的有限值域上寻找可行解并优化目标。")
lines.append("")
lines.append("对于本题，CP 将航行方案建模为一系列离散决策——路径序列、工作天数、采购量——受资源约束、载重约束、时间约束和连续作业上限约束的共同限制。通过递归回溯搜索所有可能的决策组合，同时利用三种剪枝规则提前终止不可行或次优的分支。")
lines.append("")
lines.append("## 二、CP 的三个核心机制")
lines.append("")
lines.append("### 2.1 约束传播")
lines.append("")
lines.append("在搜索的每个节点自动删除变量值域中不可能满足约束的值。例如：若 O_t < 2，则 day t+1 不能移动（燃油不够）；若当前位置不在作业点，则 act_t 的值域删除 {W}；若已连续工作 D^max 天，则下一天的值域删除 {W}。约束传播是单调的——只删除值、不添加值，保证终止。")
lines.append("")
lines.append("### 2.2 分支")
lines.append("")
lines.append("当约束传播停止且变量尚未完全确定时，选择一个变量进行分支。常用策略是\"先选值域最小的变量\"（first-fail principle）：优先处理约束最紧的变量，尽早发现冲突。在本题中，分支在\"路径骨架\"层面进行——递归尝试 {W1,W2,W3,S1,S2} 中的每个可行选项。")
lines.append("")
lines.append("### 2.3 回溯")
lines.append("")
lines.append("当某一分支导致约束冲突（值域为空）时，回溯到上一个选择点尝试其他分支。回溯确保搜索树中的所有可行解都被系统探索。")
lines.append("")
lines.append("## 三、三种剪枝规则")
lines.append("")
lines.append("**规则1——上界剪枝**：在搜索树任意节点(current_pos, t)，剩余最大Z增益为 UB_Z = (30 - t - dist(current_pos, E)) * 28。若 Z_current + UB_Z <= best_Z，整个子树被剪掉。这是CP中最强有力的剪枝——根节点上界688，随深度迅速下降。")
lines.append("")
lines.append("**规则2——相邻去重**：跳过 W3->W3 等距离为0的无意义重复。相邻相同点不消耗旅行天数却能重置连续作业计数，本质是绕过max_consec约束的漏洞。")
lines.append("")
lines.append("**规则3——前向检查**：添加点 p 前验证 travel_sofar + dist(current,p) + dist(p,E) <= 30。若不满足则从p无法在时限内抵达E。")
lines.append("")
lines.append("## 四、搜索树结构")
lines.append("")
lines.append("搜索树以 B 为根节点，每个内部节点分支5个可能的下一访问点。叶节点枚举工作天数组合并调用贪婪模拟评估。总探索节点数：313（含内部节点和叶节点），最大深度7。")
lines.append("")
lines.append("搜索树输出示例：")
lines.append("")
lines.append("| Node | Depth | Action | UpperBound | BestZ |")
lines.append("|------|-------|--------|------------|-------|")
lines.append("| 1 | 0 | branch | 688 | -Inf |")
lines.append("| 1 | 0 | leaf | 0 | 100 |")
lines.append("| 2 | 1 | branch | 576 | 100 |")
lines.append("| 3 | 2 | branch | 464 | 120 |")
lines.append("")
lines.append("上界随深度递减（688->576->464），体现了搜索从乐观估计逐渐收紧的过程。")
lines.append("")
lines.append("## 五、实验结果")
lines.append("")
lines.append("| 指标 | 值 |")
lines.append("|------|:--:|")
lines.append("| 最优 Z | 288 |")
lines.append("| 最优 M | 44 |")
lines.append("| 路径 | B->W1->S2->W3->S2->W3->E |")
lines.append("| 探索节点 | 313 |")
lines.append("| 耗时 | 0.03秒 |")
lines.append("")
lines.append("## 六、三方法对比")
lines.append("")
lines.append("| 维度 | 枚举 | 列生成 | 约束规划 |")
lines.append("|------|:---:|:---:|:---:|")
lines.append("| 搜索策略 | 穷举骨架 | 迭代添加改进列 | 递归回溯+剪枝 |")
lines.append("| 剪枝机制 | 无 | 对偶信息 | 上界+前向检查+去重 |")
lines.append("| 节点/列数 | 542骨架 | 16列 | 313节点 |")
lines.append("| 最优性保证 | 穷举 | 对偶理论 | 搜索树完备 |")
lines.append("| 可解释性 | 高 | 中 | 高 |")
lines.append("")
lines.append("## 七、方法评价")
lines.append("")
lines.append("优点：搜索树透明，每个节点可追踪；三种剪枝大幅减少搜索空间；约束表达接近题目原文；上界剪枝在大规模问题中更有价值。")
lines.append("")
lines.append("局限：需手工实现传播和搜索逻辑；递归深度受MATLAB限制（默认500）；无原生CP求解器时开发量大。")
lines.append("")
lines.append("## 八、扩展到任务3")
lines.append("")
lines.append("在任务3（30x30网格，90天，天气概率0.8/0.2）中，搜索空间急剧膨胀。CP的上界剪枝将成为关键——利用天气概率加权计算期望上界，在搜索早期剪掉大量低期望值路径。CP框架天然支持加入随机信息：在叶节点评估时调用期望值计算而非确定性模拟。")

with open(fpath, 'w', encoding='utf-8', newline='\r\n') as f:
    f.write('\n'.join(lines))
print(f'Written {len(lines)} lines')